version: 2.1
orbs:
    node: circleci/node@4.7.0
    aws-cli: circleci/aws-cli@1.3.1
    eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
    build_and_deploy:
        docker:
            - image: "cimg/base:stable"
        steps:
            - node/install:
                  node-version: "14.19.0"
            - checkout
            - run:
                  name: Install Front-End
                  command: |
                      npm run frontend:install
            - run:
                  name: Lint Front-End
                  command: |
                      npm run frontend:lint
            - run:
                  name: Build Front-End
                  command: |
                      npm run frontend:build
            - run:
                  name: Install Back-End
                  command: |
                      npm run backend:install
            - run:
                  name: Build Back-End
                  command: |
                      npm run backend:build
            - aws-cli/setup
            - eb/setup
            - run:
                  name: Deploy Back-End
                  command: npm run backend:deploy
            - run:
                  name: Deploy  Front-End
                  command: npm run frontend:deploy
workflows:
    version: 2
    deploy:
        jobs:
            - build_and_deploy
